config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :studios, only: %i[index show new create edit update] do
    resources :bookings, only: %i[new create]
  end
  namespace :owner do
    resources :bookings, only: :index
    resources :studios, only: :index
  end
  resources :bookings, only: %i[index edit update] do
    member do
      patch :accept
      patch :refuse
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :studio
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_after_start?
  # validates :end_date, presence: true, numericality: { greater_than: :start_date} # doesn't work on dates

  # validates :start_date, comparison: { greater_than: :end_date } # works only in rails 7
  enum status: {
    pending: 0,
    accepted: 1,
    refused: 2
  }

  def total_price
    (start_date.to_time.to_i - end_date.to_time.to_i).abs / 3600 * studio.price
  end

  def end_after_start?
    if start_date > end_date
      errors.add(:end_date, "should be later than the start date")
    end
  end
end

app/models/studio.rb
class Studio < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price, presence: true
  has_one_attached :photo

  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save :default_values

  has_many :studios, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :bookings_as_owner, through: :studios, source: :bookings

  def default_values
    self.name ||= self.email[...self.email.index('@')] # note self.status = 'P' if self.status.nil? might be safer (per @frontendbeauty)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    # @bookings = Booking.all
    @bookings = policy_scope(Booking)
  end

  def new
    # redirect_to new_user_session_path unless current_user
    @studio = Studio.find(params[:studio_id])
    @booking = Booking.new(studio: @studio)
    authorize @booking
  end

  def create
    update_date_params(params)
    @booking = Booking.new(booking_params)
    @studio = Studio.find(params[:studio_id])
    @booking.studio = @studio
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render "studios/show"
    end
  end

  def edit
    raise
  end

  def patch
    raise
  end

  def accept
    authorize @booking = Booking.find(params[:id])
    @booking.accepted!
    redirect_to owner_bookings_path(anchor: "owner-booking-#{@booking.id}")
  end

  def refuse
    authorize @booking = Booking.find(params[:id])
    @booking.refused!
    redirect_to owner_bookings_path(anchor: "owner-booking-#{@booking.id}")
  end

  private

  def update_date_params(params)
    date = params[:booking][:start_date]
    params[:booking][:start_date] = "#{date}T#{format('%02d', params[:start_time])}:00"
    params[:booking][:end_date] = "#{date}T#{format('%02d', params[:end_time])}:00"
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  def index
    # @bookings = Booking.all
    bookings = policy_scope([:owner, Booking])
    ## returns array of hash with keys studio_name and studio_bookings filtered by status
    @bookings = bookings.map(&:studio).uniq.map do |studio|
      { studio_name: studio.name, studio_bookings: studio.bookings }
    end
    @pending_bookings = bookings.map(&:studio).uniq.map do |studio|
      { studio_name: studio.name, studio_bookings: studio.bookings.pending }
    end
    @accepted_bookings = bookings.map(&:studio).uniq.map do |studio|
      { studio_name: studio.name, studio_bookings: studio.bookings.accepted }
    end
    @refused_bookings = bookings.map(&:studio).uniq.map do |studio|
      { studio_name: studio.name, studio_bookings: studio.bookings.refused }
    end
  end
end

app/controllers/owner/studios_controller.rb
class Owner::StudiosController < ApplicationController
  def index
    # @bookings = Booking.all
    @studios = policy_scope([:owner, Studio])
    # render "studios/index"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # raise
  end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :set_studio, only: %i[show edit update]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    # @studios = Studio.all

    @studios = policy_scope(Studio).geocoded
    @title = "All our studios"
    @search_msg = ""
    @distance_value = params[:distance] || "" # used to autofill the form
    @address_value = params[:address] || ""
    if params[:address]
      params[:distance] = params[:distance].empty? ? 2 : params[:distance]
      studios_found = @studios.near(params[:address], params[:distance])
      if studios_found.empty?
        @search_msg = "We couldn't find studios within #{params[:distance]} km of #{params[:address]}"
      else
        @studios = studios_found
        @title = "Studios within #{params[:distance]} km of #{params[:address]}"
      end
    end
    @markers = @studios.map do |studio| # @studios.geocoded.map do |studio|
      {
        lat: studio.latitude,
        lng: studio.longitude,
        info_window: render_to_string(partial: "info_window", locals: { studio: studio }),
        marker_html: render_to_string(partial: "marker", locals: { studio: studio })
      }
    end
  end

  def show
    @booking = Booking.new(start_date: Date.today) # new booking for the form
    @markers = [{ lat: @studio.latitude, lng: @studio.longitude }]
  end

  def new
    @studio = Studio.new
    authorize @studio
  end

  def create
    @studio = Studio.new(studio_params)
    @studio.user = current_user
    authorize @studio
    if @studio.save
      redirect_to "/studios/#{@studio.id}"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @studio.update(studio_params)
      redirect_to owner_studios_path(studio_params)
    else
      render :edit
    end
  end

  private

  def set_studio
    @studio = Studio.find(params[:id])
    authorize @studio
  end

  def studio_params
    # params[:studio][:user] = current_user
    params.require(:studio).permit(:name, :address, :description, :price, :photo, :user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_card.html.erb
<div class="owner-booking-card p-3 m-5 shadow">
  <div class="extra-margin-left-card">
    <h2>
      <%= booking.start_date.strftime('%m-%d-%Y')%>
      <%= booking.start_date.strftime('%H:%M')%> -
      <%= booking.end_date.strftime('%H:%M')%>
    </h2>
    <p class="text-xl text-capitalize mb-0"><%=booking.studio.name.capitalize%></p>
    <p class="text-xl">Total: ¥ <%= booking.total_price %></p>
  </div>
  <div class="owner-booking-action d-flex flex-column justify-content-evenly">
    <h2 class="text-center text-capitalize mt-5"><%= booking.status %></h2>
    <div class="d-flex justify-content-evenly">
      <%= link_to "view studio", studio_path(booking.studio), class: "studio-info-btn py-2 px-2 mb-5" %>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<% time_strings = [] %>
<% (0..12).each do |num| %>
  <% time_strings << "#{num} AM" %>
<% end %>
<% (1..11).each do |num| %>
  <% time_strings << "#{num} PM" %>
<% end %>
<%= simple_form_for [studio, booking], data: {controller: "bookingform", bookingform_price_value: studio.price}, id: "booking-form" do |f| %>
  <%#= f.input :start_date, html5: true, wrapper_html: {class: 'date-wrapper'}, label: "Time to Start Jamming" %>
  <%= f.input :start_date, as: :date, html5: true, wrapper_html: {class: 'date-wrapper mb-4'}, label: "Date" %>

  <%#= f.input :end_date, html5: true, wrapper_html: {class: 'date-wrapper'}, label: "Time to Bro Home" %>
  <div class="time-container">
    <div>
      <label for="start-time" class="form-label text-white">From</label>
      <select id="start-time"
              class="form-select"
              aria-label="Default select example"
              data-bookingform-target="startTime"
              data-action="change->bookingform#updateEndTimeSelection change->bookingform#updatePrice"
              name="start_time">
        <%# <option selected>Open this select menu</option> %>
        <option value="9" >9 AM</option>
        <option value="10">10 AM</option>
        <option value="11">11 AM</option>
        <option value="12">12 AM</option>
        <option value="13">1 PM</option>
        <option value="14">2 PM</option>
        <option value="15">3 PM</option>
        <option value="16">4 PM</option>
        <option value="17">5 PM</option>
        <option value="18">6 PM</option>
      </select>
    </div>
  <%# <input type="number"> %>

    <div>
      <label for="end-time" class="form-label text-white">To</label>
      <select id="end-time"
              class="form-select"
              aria-label="Default select example"
              data-bookingform-target="endTime"
              data-action="change->bookingform#updatePrice"
              name="end_time">
        <option value="10">10 AM</option>
        <option value="11">11 AM</option>
        <option value="12">12 AM</option>
        <option value="13">1 PM</option>
        <option value="14">2 PM</option>
        <option value="15">3 PM</option>
        <option value="16">4 PM</option>
        <option value="17">5 PM</option>
        <option value="18">6 PM</option>
        <option value="19">7 PM</option>
      </select>
    </div>
  </div>
  <%= f.submit value: "Book now!", class: "studio-booking-btn mx-auto mt-4", data: {bookingform_target: "submit"} %>
<% end %>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<%= render partial: "shared/navbar" %>
<div class="mt-5">
  <h1 class="text-center"><%= current_user.name %>'s Bookings</h1>
</div>

<% @bookings.each do |booking| %>

  <%= render partial: "card", locals: {booking: booking} %>

<% end %>

app/views/bookings/new.html.erb
<%= render partial: "shared/navbar" %>

<div class="container">
  <h1>Bookings#new</h1>
  <p>Find me in app/views/bookings/new.html.erb</p>
  <%= render partial: "form", locals: {booking: @booking, studio: @studio} %>
</div>

app/views/bookings/patch.html.erb
<h1>Bookings#patch</h1>
<p>Find me in app/views/bookings/patch.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NeighborStudio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>

    <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />
  </head>

  <body>
  <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/owner/bookings/_bigcard.html.erb
<div class="container">
  <% @bookings.each do |booking| %>
    <div class="card-studio-name">
      <h2 class="fw-bold"><%= booking[:studio_name] %></h2>
    </div>
  <% end %>
</div>

app/views/owner/bookings/_card.html.erb
<div id="owner-booking-<%= booking.id %>" class="owner-booking-card p-3 m-3 shadow">
  <div>
    <h2>
      <%= booking.start_date.strftime('%m-%d-%Y')%>
      <%= booking.start_date.strftime('%H:%M')%> -
      <%= booking.end_date.strftime('%H:%M')%>
    </h2>
    <p class="text-xl text-capitalize mb-0"><%= booking.user.name %></p>
    <p class="text-xl">Total: ¥ <%= booking.total_price %></p>
  </div>
  <div class="owner-booking-action d-flex flex-column justify-content-evenly">
    <h2 class="text-center text-capitalize"><%= booking.status %></h2>
    <div class="d-flex justify-content-evenly">
      <% if booking.pending? %>
        <%= link_to accept_booking_path(booking), method: :patch, remote: true, class: "owner-action-btn btn-accept py-2 px-3" do %>
          <p class="mb-0">
            Accept
          </p>
        <% end %>
        <%= link_to refuse_booking_path(booking), method: :patch, remote: true, class: "owner-action-btn btn-decline py-2 px-3" do %>
          <p class="mb-0">
            Decline
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/owner/bookings/index.html.erb
<%= render partial: "shared/navbar" %>

<div class="container">
  <ul class="nav nav-pills ns-nav-pills" id="studioBookingTabs" role="tablist">
    <li class="nav-item " role="presentation">
      <button class="ns-nav-link active" id="all-tab" data-bs-toggle="tab" data-bs-target="#all" type="button" role="tab" aria-controls="all aria-selected="true">All</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="ns-nav-link" id="pending-tab" data-bs-toggle="tab" data-bs-target="#pending" type="button" role="tab" aria-controls="pending" aria-selected="false">Pending</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="ns-nav-link" id="accepted-tab" data-bs-toggle="tab" data-bs-target="#accepted" type="button" role="tab" aria-controls="accepted" aria-selected="false">Accepted</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="ns-nav-link" id="refused-tab" data-bs-toggle="tab" data-bs-target="#refused" type="button" role="tab" aria-controls="refused" aria-selected="false">Refused</button>
    </li>
  </ul>
  <div class="tab-content" id="studioBookingTabs">
    <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="all-tab">
      <% @bookings.each do |booking| %>
        <div class="owner-bookings-cards">
          <div class="card-studio-name">
            <h2 class="fw-bold"><%= booking[:studio_name] %></h2>
            <% booking[:studio_bookings].each do |studio_booking| %>
              <%= render partial: "card", locals: {booking: studio_booking } %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="tab-pane fade" id="pending" role="tabpanel" aria-labelledby="pending-tab">
      <% @pending_bookings.each do |booking| %>
        <% if booking[:studio_bookings].any? %>
          <div class="owner-bookings-cards">
            <div class="card-studio-name">
              <h2 class="fw-bold"><%= booking[:studio_name] %></h2>
              <% booking[:studio_bookings].each do |studio_booking| %>
                <%= render partial: "card", locals: {booking: studio_booking } %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="tab-pane fade" id="accepted" role="tabpanel" aria-labelledby="accepted-tab">
      <% @accepted_bookings.each do |booking| %>
        <% if booking[:studio_bookings].any? %>
          <div class="owner-bookings-cards">
            <div class="card-studio-name">
              <h2 class="fw-bold"><%= booking[:studio_name] %></h2>
              <% booking[:studio_bookings].each do |studio_booking| %>
                <%= render partial: "card", locals: {booking: studio_booking } %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="tab-pane fade" id="refused" role="tabpanel" aria-labelledby="refused-tab">
      <% @refused_bookings.each do |booking| %>
        <% if booking[:studio_bookings].any? %>
          <div class="owner-bookings-cards">
            <div class="card-studio-name">
              <h2 class="fw-bold"><%= booking[:studio_name] %></h2>
              <% booking[:studio_bookings].each do |studio_booking| %>
                <%= render partial: "card", locals: {booking: studio_booking } %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/owner/studios/_card.html.erb
<div class="studio-card shadow-lg m-5 extra-margin" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.15)), url(<%= cl_image_path(studio.photo.key) %>);">
  <%= link_to edit_studio_path(studio), class: "d-flex px-4 py-2 w-100" do %>
    <div class="d-flex flex-column justify-content-end w-100 text-white">
      <div class="d-flex justify-content-between studio-info p-3">
        <div class="studio-info-left">
          <p class="mb-0 text-truncate"><%= studio.name.capitalize %></p>
          <p class="mb-0">¥<%= studio.price %>/hr</p>
        </div>
        <div class="d-flex justify-content-end">
          <div class="studio-info-btn py-2 px-2">
            <p class="mb-0 px-5">Edit</p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/owner/studios/index.html.erb
<%= render partial: "shared/navbar" %>

<div class="d-flex justify-content-between mx-5 add-studio">
  <h1 class="text-left mt-5 mb-5">Your Studios</h1>
  <div class="studio-info-btn py-2 px-2">
    <%= link_to "Add a Studio", new_studio_path, class: "btn-square py-5", id: "add-studio" %>
  </div>
</div>

<div class="h-100 row justify-content-center">
<% @studios.each do |studio| %>
  <%= render partial: "card", locals: {studio: studio}%>
<% end %>
</div>

app/views/pages/home.html.erb
<%= render partial: "shared/navbar" %>

<div class="jumbo-2">

  <div class="container float-right">
      <% if user_signed_in? %>
    <% else %>
      <p>you are not signed in</p>
    <% end %>
  </div>
  <h1 class="text-center">NeighborStudio</h1>
    <p class="text-center">Why use a home studio,
    when your Neighbor has one?</p>
  <div class="text-center mt-5">
    <%= link_to "Find studios now!", studios_path, class: "sign-up btn-square draw-border rounded mb-6" %>
  </div>

</div>

<div class="container">
  <p></p>
  <p></p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
 <nav class="ns-navbar navbar navbar-expand-lg navbar-dark bg-dark px-3 ">
    <a class="navbar-brand" href="/">NeighborStudio</a>
        <%= render "shared/search_bar" %>

    <div class="navbar-nav ">
    </div>
    </div>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav">

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav justify-content-center justify-content-lg-between w-100">
        <div class="d-flex flex-column text-center flex-lg-row">
        </div>
        <div class="nav-item dropdown d-flex justify-content-center">
          <%= image_tag "https://i.ibb.co/dbxPZsk/avatar-brian.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end text-center" aria-labelledby="navbarDropdown">
            <b>Studio Renter</b>
            <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
            <b>Studio Owner</b>
            <%= link_to "Manage Bookings", owner_bookings_path, class: "dropdown-item" %>
            <%= link_to "Manage Studios", owner_studios_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
          <div class="dropdown-menu dropdown-menu-end col-xs-1 text-center" aria-labelledby="navbarDropdown">
            <b>Studio Renter</b>
            <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
            <b>Studio Owner</b>
            <%= link_to "Manage Bookings", owner_bookings_path, class: "dropdown-item" %>
            <%= link_to "Manage Studios", owner_studios_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
      </div>
    </div>
  </nav>

app/views/shared/_search_bar.html.erb
<div class="search_bar">
  <%# form with autocomplete (deactivated) %><%#= form_with url: studios_path, method: :get, data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY']  } do |form| %>
  <%= form_with url: studios_path, method: :get do |form| %>
    <%= form.label :distance, "Find a studio within:" %>
    <%= form.text_field :distance,
                        placeholder: "2",
                        id: "distance-input",
                        value: @distance_value%>
    <%= form.label :place, "km of" %>
    <%= form.text_field :address,
                        placeholder: "Shibuya station", id: "address-input",
                        value: @address_value%>
    <%# address with extra fields for autocomplete%><%#= form.text_field :address,
                        placeholder: "Shibuya",
                        data: { geocoder_target: "address"},
                        class: "d-none" %>

    <%= form.submit "Search", id: "submit-btn"%>
  <% end %>
</div>

app/views/studios/_card.html.erb
<div class="studio-card shadow-lg mb-2" id="studio-card-<%= studio.id %>" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.15)), url(<%= cl_image_path(studio.photo.key) %>);">
  <%= link_to studio_path(studio), class: "d-flex px-4 py-2 w-100" do %>
    <div class="d-flex flex-column justify-content-end w-100 text-white">
      <div class="d-flex justify-content-between studio-info p-3">
        <div class="studio-info-left">
          <p class="mb-0 text-truncate"><%= studio.name.capitalize %></p>
          <p class="mb-0">¥<%= studio.price %>/hr</p>
        </div>
        <div class="w-50 d-flex justify-content-end">
          <div class="studio-info-btn py-2 px-2">
            <p class="mb-0">More Info</p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/studios/_form.html.erb
<div class="container">
  <div class="col-8 offset-2">
      <%= simple_form_for @studio do |f| %>
        <%= f.input :name, placeholder: "Beautiful sound proof studio near Shibuya station" %>
        <%= f.input :address, placeholder: "00-00-0, Jingu-mae, Shibuya-ku, Tokyo, 1500001" %>
        <%= f.input :description, placeholder: "It is near from Shibuya-station." %>
        <%= f.input :price, label: "Price (¥/hour)", placeholder: "1000" %>
        <%= f.input :photo, as: :file %>
        <%= f.submit 'Submit', class: "btn btn-dark"%>
      <% end %>
  </div>
</div>

app/views/studios/_info_window.html.erb
<div class="studio-card-small shadow-lg m-2" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.15)), url(<%= cl_image_path(studio.photo.key, crop: :fill, width: 210, height: 140) %>);">
  <%= link_to studio_path(studio), class: "" do %>


    <div>
      <p><%= studio.name.capitalize %></p>
      <p><strong>¥<%= studio.price %>/hr</strong></p>
    </div>


  <% end %>
</div>

app/views/studios/_marker.html.erb
<div class="price-container" data-studio-id="<%= studio.id %>">
  <p><strong>¥<%= studio.price %></strong></p>
</div>
<i class="fas fa-caret-down"></i>

app/views/studios/create.html.erb
<h1>Studios#create</h1>
<p>Find me in app/views/studios/create.html.erb</p>

app/views/studios/edit.html.erb
<%= render "shared/navbar" %>
<div class="container justify-content-center">
  <h1 class="text-center">Edit your studio</h1>
  <%= render "form" %>
</div>

app/views/studios/index.html.erb
  <%= render partial: "shared/navbar" %>

<div class="search_msg">
  <p><%= @search_msg %></p>
</div>

<h1 class="text-center mt-4git "><%= @title %></h1>
<div class="main-container">
  <div class="container-fluid mt-4">
    <div class="studios-list col-xs-6">
      <% @studios.each do |studio| %>
        <%= render partial: "card", locals: {studio: studio}%>
      <% end %>
    </div>
  </div>
  <%# Note: the map uses a custom sidebar instead of the bootstrap one,
  because the bootstrap sticky has a z-index on top of the avatar dropdown %>
  <div class="mt-4 mr-5 pr-5"
    id="sidebar"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
    style='width: 100%; height: 600px;'>
  </div>
</div>

app/views/studios/new.html.erb
<%= render "shared/navbar" %>
<div class="container justify-content-center">
  <h1 class="text-center">Register a new studio</h1>
  <%= render "studios/form" %>
</div>

app/views/studios/show.html.erb
<%= render partial: "shared/navbar" %>

<div class="container">
  <div class="row">
    <div class="col-8">
      <h1 class="text-capitalize"><%= @studio.name %></h1>
      <p>
        <%= @studio.description %>
      </p>
      <%= cl_image_tag @studio.photo.key, crop: :fill, class: "img-responsive p-1" %>
      <div
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        style='width: 100%; height: 500px;'
        class="mb-5 mt-5">
      </div>
    </div>
    <div class="col-4">
      <div class="studio-booking-form shadow p-5">
        <div>
          <p class="text-label">
            <span class="text-lg text-white"><i class="fas fa-map me-2"></i>Address: </span><%= @studio.address %>
          </p>
          <p id="user-distance" class="text-label">
            <span class="text-lg text-white"><i class="fas fa-map-marked-alt me-2"></i>Distance: </span>N/A
          </p>
          <p class="text-label">
            <span class="text-lg text-white"><i class="fas fa-tag me-2"></i>Price: </span>¥<%= @studio.price %>/hr
          </p>
        </div>
        <div>
          <%= render partial: "bookings/form", locals: {booking: @booking, studio: @studio} %>
        </div>
      </div>
    </div>
  </div>
</div>